### ISSUE TITLE
Error when podcast strats playing

### ISSUE THREAD

**Issue by de666** [tkem/mopidy-podcast#54]
I get this error when I try to play something from one of my podcast

```
ERROR    Triggering event failed: stream_changed(uri)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/listener.py", line 45, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy/core/actor.py", line 95, in stream_changed
    self.playback._on_stream_changed(uri)
  File "/usr/lib/python2.7/site-packages/mopidy/core/playback.py", line 230, in _on_stream_changed
    self._trigger_track_playback_started()
  File "/usr/lib/python2.7/site-packages/mopidy/core/playback.py", line 581, in _trigger_track_playback_started
    self.core.history._add_track(tl_track.track)
  File "/usr/lib/python2.7/site-packages/mopidy/core/history.py", line 35, in _add_track
    ', '.join([artist.name for artist in track.artists]))
TypeError: sequence item 0: expected string or Unicode, NoneType found

```

the complete URI is the following

`podcast+http://www.radio24.ilsole24ore.com/podcast/lazanzara.xml#http://audio.radio24.ilsole24ore.com/radio24_audio/2018/180713-lazanzara-s.mp3`

Any solutions for this?

**Comment by tkem** [comment]
Probably caused by an empty `<itunes:author>` tag in the podcast XML:

```
<item>
<title><![CDATA[La Zanzara del giorno 13/07/2018: Diciottoli]]></title><link>http://audio.radio24.ilsole24ore.com/radio24_audio/2018/180713-lazanzara-s.mp3</link><description><![CDATA[Mattarella chiama e Conte risponde ...]]></description><itunes:author></itunes:author><enclosure length="10000" type="audio/mpeg" url="http://audio.radio24.ilsole24ore.com/radio24_audio/2018/180713-lazanzara-s.mp3"></enclosure><pubDate>Fri, 13 Jul 2018 20:56:40 +0200</pubDate><guid>http://audio.radio24.ilsole24ore.com/radio24_audio/2018/180713-lazanzara-s.mp3</guid></item>

```
Though the exception is raised in Mopidy's history module, which is unrelated, this probably should be filtered by the mopidy-podcast extension (I thought it was already).
